config/routes.rb
Rails.application.routes.draw do
  
  resources :candidates
  resources :firms
  resources :profiletags
  resources :tags
  resources :profiles
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

  devise_scope :user do
    get "/login" => "devise/sessions#new", as: "login"
    get "/logout" => "devise/sessions#destroy"
    get "/join" => "devise/registrations#new"
  end

  get '/add_profile', to: 'profiles#add_profile', as: "add_profile"
  
  get '/get_schools', to: 'profiles#get_schools'

  get '/admin_dash/:name', to: 'firms#admin_dash', as: "admin_dash"

  post '/upload_resume', :to => "profiles#upload_resume"

  post '/upload_picture', :to => "profiles#upload_picture"

  post '/update_tags', :to => "profiles#update_tags"

  post '/update_position', :to => "candidates#update_position"

  post '/dash_filter',:to => "firms#dash_filter"

  get '/apply/:name', :to => "firms#apply"

  get '/download_book/:firm_id', :to => "firms#download_book", as: "download_book"

  get '/download_xls', :to => "firms#download_xls", as: "download_xls"

  root 'static_pages#home'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base

	belongs_to :firm
	belongs_to :profile

	require "csv"

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names + ["Name","School","Year","Major","Resume","GPA"]
	    all.each do |product|
	      csv << product.attributes.values_at(*column_names) + [product.profile.user.full_name, product.profile.school, product.profile.year, product.profile.major, product.profile.resume, product.profile.gpa]
	    end
	  end
	end
	
end

app/models/firm.rb
class Firm < ActiveRecord::Base

	has_many :candidates
	has_many :profiles, through: :candidates


end

app/models/profile.rb
class Profile < ActiveRecord::Base

	#attr_accessible :image, :resume, :school, :major, :year
	
	belongs_to :user

	has_many :profiletags
	has_many :tags, through: :profiletags

	has_many :candidates
	has_many :firms, through: :candidates

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |product|
	      csv << product.attributes.values_at(*column_names)
	    end
	  end
	end

end

app/models/profiletag.rb
class Profiletag < ActiveRecord::Base

	belongs_to :profile
	belongs_to :tag
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_many :profiletags
	has_many :profiles, through: :profiletags

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :profile, dependent: :destroy

    validates :firstname, presence: true
    validates :lastname, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 8 } 

	def full_name
		self.firstname.strip.capitalize + " " + self.lastname.strip.capitalize
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
	add_profile_path
  end


end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

	def update_position
		@firm = Firm.find_by_name("apollo")
		@candidate = current_user.profile.candidates.find_by_firm_id(@firm.id)
		if params["position"]
			@candidate.position = params["position"]
			@candidate.save
		end
		redirect_to add_profile_path
	end

	private
		def candidate_params
			params.require(:candidate).permit(:profile_id, :firm_id, :position)
		end


end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController

	before_filter :auth, :only => [:admin_dash, :download_book, :dash_filter, :download_xls]
	before_filter :authenticate_user!, :except => [:apply, :admin_dash, :download_book, :dash_filter, :download_xls]

	require 'combine_pdf'

	def auth
    	authenticate_or_request_with_http_basic('Administration') do |username, password|
      		username == 'admin' && password == 'tenderoffer'
    	end
  	end


	def apply
		@firm = Firm.find_by_name(params[:name])
		@minimum_password_length = 8
	end

	def admin_dash
		@firm = Firm.find_by_name(params[:name])
		if params["position"]
			@positions = params["position"].split(', ')
			@candidates = @firm.candidates.where("position IN (:pos) ", pos: @positions)
		else
			@candidates = @firm.candidates
		end
		
	end

	def download_xls
		@candidates = Candidate.all
		send_data @candidates.to_csv
	end

	def download_book
		@candidate = Candidate.find(params[:firm_id])

		# pdf = CombinePDF.new
		# @candidates.each do |candidate|
		# 	if candidate.profile.resume
		# 		pdf << CombinePDF.parse(Net::HTTP.get(URI.parse(candidate.profile.resume)))
		# 		send_data pdf.to_pdf, filename: "{candidate.profile.user.full_name}"+"_resume", type: "application/pdf"
		# 	end
		# end
		#send_data pdf.to_pdf, filename: "combined_resume_book.pdf", type: "application/pdf"

		if @candidate.profile.resume
			send_data @candidate.profile.resume,
			    :filename => "#{@candidate.profile.user.full_name}.pdf",
			    :type => "application/pdf"
		end
	end

	def dash_filter
		if params["position"]
			redirect_to admin_dash_path(name: "apollo", position: params["position"].map{|e| e[0]}.join(", "))
		else
			redirect_to :back
		end
	end


	private
		def firm_params
			params.require(:firm).permit(:name)
		end


end

app/controllers/profiletags_controller.rb
class ProfiletagsController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 
  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end

  def create
  	if params["access_code"] == "itsnowover"
      super
      if current_user
  	  	profile = Profile.create(user_id: current_user.id)
  	  	if params["firm_name"]
  	  		Candidate.create(profile_id: profile.id, firm_id: Firm.find_by_name(params["firm_name"]).id)
  	  	end
      end
  	else
  		redirect_to :back
  	end

  end

  private


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		redirect_to "/apply/apollo"
	end

	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		redirect_to root_path
	end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/profiletags_helper.rb
module ProfiletagsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/firms/admin_dash.html.erb
<div class="container" align="center">
	<div class="title">
		Candidate Dashboard
	</div>
	<div class="sub-title">
		<i><%= @candidates.count %> applications submitted</i>
		<hr>
	</div>
		<div class="row" id="filterrow">
		<div class="col-md-2">
		</div>
		<div class="col-md-2">
		</div>
		<div class="col-md-2">
		</div>
		<div class="col-md-1">
		</div>
		<div class="col-md-3">
			<a href="<%=download_xls_path%>" type="button" class="btn btn-default">Download XLS</a>
		</div>
		<div class="col-md-2">
			<div class="dropdown filters">
			  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
			    Filter By Position
			    <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" align="left">
			  	<%= form_tag(:action => "dash_filter", :controller => "firms") do %>
				  	<% ["credit", "private equity", "real estate"].each do |position| %>
					    <li> <%= check_box_tag "position[#{position}]" %> <%= label_tag "position[#{position}]", "#{position.capitalize}" %></li>
				    <% end %>
				  	<%= submit_tag "Filter" %>
				<% end %>
				<li class="pad"> <u><a href="<%=admin_dash_path(@firm.name)%>">Reset filters </a></u></li>
			  </ul>
			</div>
		</div>
	</div>
	<hr>
		<% @candidates.each_slice(3) do |slice| %>
			<div class="row">
				<% slice.each do |candidate| %>
					<div class="col-md-4">
						<div class="profile-box" style="min-height:200px;">
							<div class="profile-name">
								<%= candidate.profile.user.full_name %>
							</div>
							<br>
							<div>
								<%= candidate.profile.school %>
							</div>
							<div>
								<% if candidate.profile.year %>
									Graduating in <%= candidate.profile.year %>
								<% end %>
							</div>
							<div>
								<% if candidate.profile.major %>
									Major: <%= candidate.profile.major.capitalize %>
								<% end %>
							</div>
							<div>
								<% if candidate.profile.gpa %>
									GPA: <%= candidate.profile.gpa %>
								<% end %>
							</div>
							<div>
								<% if candidate.position %>
									Interested in: <%= candidate.position %> 
								<% end %>
							</div>
							<div>
								<% if candidate.profile.profiletags.first %>
									Interested in: <%= candidate.profile.tags.map(&:name).join(', ') %> 
								<% end %>
							</div>
							<br>
							<div>
								<% if candidate.profile.resume %>
									<u><a href="<%=candidate.profile.resume%>" target="_blank">Click to view <%= candidate.profile.user.firstname.capitalize %>'s resume</a></u>
									<br>
									<a href="<%=download_book_path(candidate.id)%>" type="button" class="btn btn-default">Download Resume</a>
								<% else %>
									No Resume Uploaded
								<% end %>
							</div>
						</div>
					</div>
				<% end %>	
			</div>
		<% end %>		
</div>

app/views/firms/apply.html.erb
  <div class="container" align="center">
    <div class="devise-box">
      <div class="devise-header">
        Apply for a position at <%= @firm.name.capitalize %>
        <hr>
      </div>
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :validate => true) do |f| %>
        <div class="row-fluid">
          <div class="col-md-6">
            <div class="field">
              <%= f.label :firstname, "First Name" %><br />
              <%= f.text_field :firstname, autofocus: true %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= f.label :lastname, "Last Name" %><br />
              <%= f.text_field :lastname, autofocus: true %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= label_tag "access_code", "Application Code" %><br />
              <%= text_field_tag "access_code" %>
              <%= hidden_field_tag "firm_name", "#{@firm.name}" %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <i>(<%= @minimum_password_length %> characters minimum)</i>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", :validate => { :presence => true, :confirmation => true } %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", :validate => true %>
            </div>
          </div>
        </div>
        <div class="actions">
          <%= f.submit "Sign up", :style => "margin-top:20px;" %>
        </div>
      <% end %>
      <br>
      <%= render "devise/shared/links" %>
    </div>
  </div>